"""Community Information & Safety models.

Panchayat-managed civic information content: government scheme listings, local
news / Panchayat announcements, and safety/awareness resources (drug awareness,
community safety, women's safety).

All content is user-generated by the Panchayat. Nothing here is ever claimed to
be government-authenticated or fabricated; external links are treated as
references only.
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text, func, text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.models.enums import (
    NoticeSource,
    NoticeType,
    PublishStatus,
    SafetyResourceType,
    SafetySection,
    SchemeCategory,
    SchemeStatus,
)
from app.models.types import db_enum


class Scheme(Base):
    """A Panchayat-published government scheme information listing."""

    __tablename__ = "schemes"

    id: Mapped[int] = mapped_column(primary_key=True)
    category: Mapped[SchemeCategory] = mapped_column(
        db_enum(SchemeCategory, "scheme_category"),
        nullable=False,
        default=SchemeCategory.OTHER,
    )
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    short_description: Mapped[str] = mapped_column(Text, nullable=False)
    detailed_description: Mapped[str | None] = mapped_column(Text)
    eligibility: Mapped[str | None] = mapped_column(Text)
    benefits: Mapped[str | None] = mapped_column(Text)
    required_documents: Mapped[str | None] = mapped_column(Text)
    application_instructions: Mapped[str | None] = mapped_column(Text)
    official_url: Mapped[str | None] = mapped_column(String(500))
    deadline: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    state: Mapped[str | None] = mapped_column(String(120))
    district: Mapped[str | None] = mapped_column(String(120))
    village_id: Mapped[int | None] = mapped_column(
        ForeignKey("villages.id", ondelete="RESTRICT"), index=True
    )
    target_groups: Mapped[str | None] = mapped_column(String(255))
    status: Mapped[SchemeStatus] = mapped_column(
        db_enum(SchemeStatus, "scheme_status"),
        nullable=False,
        default=SchemeStatus.DRAFT,
        server_default=text("'draft'"),
    )
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_by: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="RESTRICT"))
    original_language: Mapped[str] = mapped_column(
        String(8), nullable=False, default="en", server_default=text("'en'")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    village = relationship("Village", foreign_keys=[village_id])
    creator = relationship("User", foreign_keys=[created_by])


class CommunityNotice(Base):
    """A Panchayat announcement, local/community notice, or external news reference."""

    __tablename__ = "community_notices"

    id: Mapped[int] = mapped_column(primary_key=True)
    notice_type: Mapped[NoticeType] = mapped_column(
        db_enum(NoticeType, "notice_type"),
        nullable=False,
        default=NoticeType.ANNOUNCEMENT,
    )
    source_type: Mapped[NoticeSource] = mapped_column(
        db_enum(NoticeSource, "notice_source"),
        nullable=False,
        default=NoticeSource.PANCHAYAT,
    )
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    summary: Mapped[str | None] = mapped_column(Text)
    content: Mapped[str | None] = mapped_column(Text)
    category: Mapped[str | None] = mapped_column(String(80))
    is_featured: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=text("false")
    )
    state: Mapped[str | None] = mapped_column(String(120))
    district: Mapped[str | None] = mapped_column(String(120))
    village_id: Mapped[int | None] = mapped_column(
        ForeignKey("villages.id", ondelete="RESTRICT"), index=True
    )
    status: Mapped[PublishStatus] = mapped_column(
        db_enum(PublishStatus, "publish_status"),
        nullable=False,
        default=PublishStatus.DRAFT,
        server_default=text("'draft'"),
    )
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_by: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="RESTRICT"))
    original_language: Mapped[str] = mapped_column(
        String(8), nullable=False, default="en", server_default=text("'en'")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    village = relationship("Village", foreign_keys=[village_id])
    creator = relationship("User", foreign_keys=[created_by])


class SafetyResource(Base):
    """Safety/awareness content: drug awareness, community safety, women's safety.

    ``HELP_RESOURCE`` items carry an official support contact / external URL so
    the module stays informational. The physical emergency-button workflow is a
    future integration point and is intentionally NOT implemented here.
    """

    __tablename__ = "safety_resources"

    id: Mapped[int] = mapped_column(primary_key=True)
    section: Mapped[SafetySection] = mapped_column(
        db_enum(SafetySection, "safety_section"),
        nullable=False,
        default=SafetySection.COMMUNITY_SAFETY,
    )
    resource_type: Mapped[SafetyResourceType] = mapped_column(
        db_enum(SafetyResourceType, "safety_resource_type"),
        nullable=False,
        default=SafetyResourceType.ARTICLE,
    )
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    summary: Mapped[str | None] = mapped_column(Text)
    content: Mapped[str | None] = mapped_column(Text)
    external_url: Mapped[str | None] = mapped_column(String(500))
    contact_label: Mapped[str | None] = mapped_column(String(120))
    contact_phone: Mapped[str | None] = mapped_column(String(40))
    is_featured: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=text("false")
    )
    state: Mapped[str | None] = mapped_column(String(120))
    district: Mapped[str | None] = mapped_column(String(120))
    village_id: Mapped[int | None] = mapped_column(
        ForeignKey("villages.id", ondelete="RESTRICT"), index=True
    )
    status: Mapped[PublishStatus] = mapped_column(
        db_enum(PublishStatus, "publish_status"),
        nullable=False,
        default=PublishStatus.DRAFT,
        server_default=text("'draft'"),
    )
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_by: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="RESTRICT"))
    original_language: Mapped[str] = mapped_column(
        String(8), nullable=False, default="en", server_default=text("'en'")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    village = relationship("Village", foreign_keys=[village_id])
    creator = relationship("User", foreign_keys=[created_by])
