import 'package:flutter/material.dart';

/// GramOne Localization Service — singleton ChangeNotifier.
/// Covers 13 Indian languages with 100+ keys per language.
/// Usage from any widget's build():  context.tr('key', fallback: 'Default')
/// The service is a singleton: LocalizationService()  (factory constructor)
class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  String _currentLocale = 'en';
  String get currentLocale => _currentLocale;
  bool get isRtl => _currentLocale == 'ur';
  TextDirection get textDirection => isRtl ? TextDirection.rtl : TextDirection.ltr;

  void setLocale(String localeCode) {
    if (_currentLocale != localeCode) {
      _currentLocale = localeCode;
      notifyListeners();
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // TRANSLATION DICTIONARY — 13 languages × 120+ keys
  // ─────────────────────────────────────────────────────────────────────────
  static const Map<String, Map<String, String>> _strings = {

    // ── ENGLISH ────────────────────────────────────────────────────────────
    'en': {
      // App shell
      'app_title': 'GramOne',
      'app_tagline': 'Civic Governance & CSR Infrastructure',
      // Nav tabs
      'citizen_tab': 'Home', 'my_reports': 'My Issues', 'report_issue': 'Report',
      'alerts_tab': 'Alerts', 'admin_tab': 'Admin HQ', 'worker_tab': 'My Tasks',
      'csr_tab': 'CSR', 'projects_tab': 'Projects', 'staff_tab': 'Staff',
      'queue_tab': 'Issue Queue', 'emergency_tab': 'Emergency',
      'discover_tab': 'Discover', 'sponsorships_tab': 'Sponsorships',
      'block_hq_tab': 'Block HQ', 'escalations_tab': 'Escalations',
      'analytics_tab': 'Analytics', 'district_hq_tab': 'District HQ',
      'audit_tab': 'Audit', 'funding_tab': 'Funding', 'state_hq_tab': 'State HQ',
      'policy_tab': 'Policy', 'disaster_tab': 'Disaster', 'attendance_tab': 'Attendance',
      'work_queue_tab': 'Work Queue', 'profile_tab': 'Profile',
      // Dashboard headers
      'citizen_dashboard_title': 'GramOne Citizen',
      'panchayat_dashboard_title': 'Panchayat Admin Console',
      'employee_dashboard_title': 'Field Worker Portal',
      'csr_dashboard_title': 'CSR Partner Hub',
      'block_dashboard_title': 'Block Officer HQ',
      'district_dashboard_title': 'District Collector HQ',
      'state_dashboard_title': 'State Secretariat HQ',
      // Citizen dashboard
      'report_civic_issue': 'Report a Civic Issue',
      'ai_detect_desc': 'AI detects urgency & assigns nearest field technician.',
      'new_report': 'New Report',
      'recent_panchayat_issues': 'Recent Panchayat Issues',
      'village_projects': 'Village Projects',
      'view_all': 'View All',
      'my_reports_count': 'My Reports',
      'resolved': 'Resolved',
      'active_csr': 'Active CSR',
      // Status strings
      'status_pending': 'Pending Triage',
      'status_in_progress': 'In Progress',
      'status_resolved': 'Resolved',
      'status_rejected': 'Rejected',
      'status_critical': 'Critical Alert',
      // Category strings
      'cat_water': 'Water Supply',
      'cat_sanitation': 'Sanitation',
      'cat_roads': 'Roads & Infrastructure',
      'cat_electricity': 'Electricity',
      'cat_environment': 'Environment',
      // Issue reporting
      'report_step1_title': 'Report Issue — Step 1 of 3',
      'describe_problem': 'Describe the problem',
      'describe_hint': 'Provide details about location and what needs repair.',
      'category_label': 'Category',
      'issue_title_label': 'Issue Title',
      'issue_title_hint': 'e.g. Water pipe leakage near community well',
      'detailed_desc_label': 'Detailed Description',
      'detailed_desc_hint': 'Describe severity, landmark, and duration...',
      'next_attach_photo': 'Next: Attach Photo',
      'upload_evidence': 'Upload evidence photo',
      'upload_hint': 'Photos help AI classify severity and speed up dispatch.',
      'tap_to_photo': 'Tap to take photo or upload from gallery',
      'run_ai': 'Run AI Diagnostics',
      'submit_report': 'Submit Report',
      'report_submitted': 'Report Submitted!',
      'report_submitted_desc': 'Your ticket has been created. Track updates on your dashboard timeline.',
      // Employee portal
      'field_worker_portal': 'Field Worker Portal',
      'assigned_work': 'Assigned Work',
      'tasks': 'Tasks',
      'high_priority': 'High Priority',
      'completed_tasks': 'Completed',
      'this_month': 'This Month',
      'my_field_assignments': 'My Field Assignments',
      'assigned_field_work': 'Assigned Field Work',
      'accept_work': 'Accept Work Assignment',
      'fill_inspection': 'Fill Inspection Form',
      'confirm_dispatch': 'Confirm Dispatch Acceptance',
      'confirm_dispatch_desc': 'Accepting will notify citizen and Panchayat admin that you are en route.',
      'confirm_start_nav': 'Confirm & Start Navigation',
      'field_inspection_title': 'Field Inspection Form',
      'technical_cause': 'Technical Cause Identified',
      'repair_time': 'Estimated Repair Time (Hours)',
      'materials_required': 'Materials Required',
      'save_inspection': 'Save Inspection Notes',
      'upload_before_photo': 'Upload Before Repair Photo',
      'proceed_completion': 'Proceed to Work Completion',
      'upload_after_photo': 'Upload After Repair Photo',
      'submit_completion': 'Submit Work Completion',
      'work_completed': 'Work Completed!',
      'work_completed_desc': 'Panchayat Admin has been requested for final verification.',
      'back_to_worker_dashboard': 'Back to Worker Dashboard',
      'daily_attendance': 'Daily Attendance Status',
      'checked_in_field': 'Status: Checked In — On Field',
      'attendance_time': 'Time: 08:30 AM • GPS Location Verified',
      'check_out_today': 'Check Out for Today',
      // Admin
      'admin_console': 'Administrative Controls',
      'issue_queue': 'Issue Queue',
      'impact_cases': 'Impact Cases',
      'employees': 'Employees',
      'attendance': 'Attendance',
      'iot_hardware': 'IoT Hardware',
      'emergency_sos': 'Emergency SOS',
      'pending_queue': 'Pending Queue',
      'critical_ai_alerts': 'Critical AI Alerts',
      'active_workers': 'Active Workers',
      'attendance_pct': 'Attendance',
      'csr_projects': 'CSR Projects',
      'open_sponsorships': 'Open Sponsorships',
      'iot_devices': 'IoT Devices',
      'gas_anomaly': 'Gas Anomaly Alert',
      'urgent_issues': 'Urgent Issues Queue',
      'see_queue': 'See Queue',
      'assign_employee': 'Assign Employee',
      'assign_btn': 'Assign Employee',
      'verify_field_work': 'Verify Completed Field Work',
      'approve_close': 'Approve & Close Ticket',
      'before_after_compare': 'Before & After Photo Comparison',
      'ai_score': 'AI Score',
      // Analytics
      'resolution_rate': 'Total Resolution Rate',
      'avg_resolution': 'Avg Resolution Speed',
      'ai_automated': 'AI automated dispatch',
      // Profile & Settings
      'user_profile': 'User Profile',
      'edit_profile': 'Edit Profile',
      'change_language': 'Change Language',
      'accessibility_settings': 'Accessibility Settings',
      'app_settings': 'App Settings',
      'help_support': 'Help & Support',
      'about_gramone': 'About GramOne',
      'sign_out': 'Sign Out',
      'save_changes': 'Save Changes',
      'full_name': 'Full Name',
      'email': 'Email',
      'phone': 'Phone Number',
      // Auth
      'welcome_back': 'Welcome back',
      'sign_in_desc': 'Enter your registered credentials or mobile number.',
      'phone_email': 'Phone number or email',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'sign_in': 'Sign in',
      'no_account': "Don't have an account? ",
      'create_account': 'Create account',
      'join_gramone': 'Join GramOne',
      'register_desc': 'Register your citizen or administrative profile.',
      'mobile_number': 'Mobile number',
      'panchayat_name': 'Gram Panchayat name',
      'send_otp': 'Send OTP Verification',
      // Onboarding
      'onboarding1_title': 'Report Civic Issues Instantly',
      'onboarding1_body': 'Capture water, road, or sanitation problems in your Gram Panchayat with AI-driven severity scoring.',
      'onboarding2_title': 'Transparent Panchayat Operations',
      'onboarding2_body': 'Track field work status, employee verification, and village project milestones in real-time.',
      'onboarding3_title': 'CSR Impact & IoT Telemetry',
      'onboarding3_body': 'Discover high-impact sponsorship opportunities and monitor rural smart hardware metrics.',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      // Role selection
      'welcome_to_gramone': 'Welcome to GramOne',
      'select_role': 'Select your operational role to continue.',
      'role_citizen': 'Citizen',
      'role_citizen_desc': 'Report problems, track status, view local civic progress',
      'role_admin': 'Panchayat Admin',
      'role_admin_desc': 'Manage issue queue, assign workers, review impact cases',
      'role_block': 'Block Officer',
      'role_block_desc': 'Cross-panchayat analytics, escalation review, performance tracking',
      'role_district': 'District Officer',
      'role_district_desc': 'Block performance, funding approvals, district emergency',
      'role_state': 'State HQ Officer',
      'role_state_desc': 'State analytics, policy monitoring, district ranking',
      'role_employee': 'Panchayat Field Employee',
      'role_employee_desc': 'Inspect work sites, upload photos, confirm completed work',
      'role_csr': 'CSR Partner / Sponsor',
      'role_csr_desc': 'Discover high impact projects, sponsor initiatives, track metrics',
      // Language screen
      'select_language': 'Select Language / भाषा चुनें',
      'choose_language': 'Choose your preferred language',
      'confirm_language': 'Confirm Language',
      'change_app_language': 'Change App Language',
      // Notifications
      'notifications': 'Notifications',
      // Feedback
      'rate_resolution': 'Rate Resolution Quality',
      'submit_feedback': 'Submit Feedback',
      // RBAC
      'unauthorized_access': 'Access Denied',
      'unauthorized_msg': 'Your account role does not have permission to access this screen.',
      'back_to_dashboard': 'Back to Dashboard',
      // Offline
      'offline_banner': 'Offline — Changes sync automatically when online',
      // CSR
      'discover_opportunities': 'Discover CSR Opportunities',
      'active_sponsorships': 'Active Sponsorships',
      'impact_tracking': 'Impact Tracking',
      // Block Officer
      'block_label': 'Block',
      'panchayats_label': 'Panchayats',
      'escalated_cases': 'Escalated Cases',
      'block_resolution_rate': 'Block Resolution Rate',
      'budget_utilization': 'Budget Utilization',
      'avg_field_response': 'Avg Field Response',
      'panchayat_performance': 'Panchayat Performance — This Block',
      'escalated_awaiting': 'Escalated Cases Awaiting Block Approval',
      // District Officer
      'district_label': 'District',
      'pending_approvals': 'Pending Approvals',
      'district_csr_fund': 'District CSR Fund',
      'active_audit': 'Active Audit Reports',
      'block_performance': 'Block Performance Ranking',
      'funding_approvals': 'Pending Funding Approvals',
      'approve': 'Approve',
      // State Officer
      'statewide': 'Statewide',
      'districts_at_risk': 'Districts At Risk',
      'state_csr': 'State CSR Mobilization',
      'iot_online': 'IoT Devices Online',
      'district_ranking': 'District Performance Ranking',
      'export': 'Export',
      'policy_mandates': 'Active Policy Mandates',
      'state_emergency_btn': 'Open State Emergency Control Room',
      // General
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'retry': 'Retry',
      'loading': 'Loading...',
      'no_data': 'No data available',
      'error_occurred': 'Something went wrong',
    },

    // ── HINDI ──────────────────────────────────────────────────────────────
    'hi': {
      'app_title': 'ग्रामवन', 'app_tagline': 'नागरिक शासन और सीएसआर अवसंरचना',
      'citizen_tab': 'होम', 'my_reports': 'मेरी शिकायतें', 'report_issue': 'रिपोर्ट करें',
      'alerts_tab': 'अलर्ट', 'admin_tab': 'प्रशासन', 'worker_tab': 'मेरे कार्य',
      'csr_tab': 'सीएसआर', 'projects_tab': 'परियोजनाएं', 'staff_tab': 'कर्मचारी',
      'queue_tab': 'शिकायत सूची', 'emergency_tab': 'आपातकाल',
      'discover_tab': 'खोजें', 'sponsorships_tab': 'प्रायोजन',
      'block_hq_tab': 'ब्लॉक मुख्यालय', 'escalations_tab': 'वृद्धि',
      'analytics_tab': 'विश्लेषण', 'district_hq_tab': 'जिला मुख्यालय',
      'audit_tab': 'ऑडिट', 'funding_tab': 'वित्त', 'state_hq_tab': 'राज्य मुख्यालय',
      'policy_tab': 'नीति', 'disaster_tab': 'आपदा', 'attendance_tab': 'उपस्थिति',
      'work_queue_tab': 'कार्य सूची', 'profile_tab': 'प्रोफ़ाइल',
      'citizen_dashboard_title': 'ग्रामवन नागरिक',
      'panchayat_dashboard_title': 'पंचायत प्रशासक',
      'employee_dashboard_title': 'क्षेत्र कार्यकर्ता पोर्टल',
      'csr_dashboard_title': 'सीएसआर भागीदार केंद्र',
      'block_dashboard_title': 'ब्लॉक अधिकारी',
      'district_dashboard_title': 'जिला कलेक्टर',
      'state_dashboard_title': 'राज्य सचिवालय',
      'report_civic_issue': 'नागरिक समस्या दर्ज करें',
      'ai_detect_desc': 'AI तात्कालिकता का पता लगाता है और निकटतम तकनीशियन को भेजता है।',
      'new_report': 'नई रिपोर्ट',
      'recent_panchayat_issues': 'हाल की पंचायत समस्याएं',
      'village_projects': 'ग्राम परियोजनाएं',
      'view_all': 'सभी देखें',
      'my_reports_count': 'मेरी रिपोर्ट',
      'resolved': 'हल हो गया',
      'active_csr': 'सक्रिय सीएसआर',
      'status_pending': 'लंबित जांच',
      'status_in_progress': 'प्रगति पर',
      'status_resolved': 'हल हो गया',
      'status_rejected': 'अस्वीकृत',
      'status_critical': 'गंभीर चेतावनी',
      'cat_water': 'जल आपूर्ति',
      'cat_sanitation': 'स्वच्छता',
      'cat_roads': 'सड़कें और बुनियादी ढांचा',
      'cat_electricity': 'बिजली',
      'cat_environment': 'पर्यावरण',
      'report_step1_title': 'समस्या रिपोर्ट — चरण 1 / 3',
      'describe_problem': 'समस्या का विवरण दें',
      'describe_hint': 'स्थान और मरम्मत के बारे में विवरण प्रदान करें।',
      'category_label': 'श्रेणी',
      'issue_title_label': 'समस्या शीर्षक',
      'issue_title_hint': 'उदा. सामुदायिक कुएं के पास पाइप रिसाव',
      'detailed_desc_label': 'विस्तृत विवरण',
      'detailed_desc_hint': 'गंभीरता, स्थान और अवधि का वर्णन करें...',
      'next_attach_photo': 'अगला: फ़ोटो संलग्न करें',
      'upload_evidence': 'साक्ष्य फ़ोटो अपलोड करें',
      'upload_hint': 'फ़ोटो AI को गंभीरता वर्गीकृत करने और तेजी से भेजने में मदद करती है।',
      'tap_to_photo': 'फ़ोटो लेने या गैलरी से अपलोड करने के लिए टैप करें',
      'run_ai': 'AI निदान चलाएं',
      'submit_report': 'रिपोर्ट सबमिट करें',
      'report_submitted': 'रिपोर्ट सबमिट हो गई!',
      'report_submitted_desc': 'आपका टिकट बनाया गया है। डैशबोर्ड पर अपडेट ट्रैक करें।',
      'field_worker_portal': 'क्षेत्र कार्यकर्ता पोर्टल',
      'assigned_work': 'सौंपे गए कार्य',
      'tasks': 'कार्य',
      'high_priority': 'उच्च प्राथमिकता',
      'completed_tasks': 'पूर्ण',
      'this_month': 'इस महीने',
      'my_field_assignments': 'मेरे क्षेत्र कार्य',
      'assigned_field_work': 'सौंपा गया क्षेत्र कार्य',
      'accept_work': 'कार्य स्वीकार करें',
      'fill_inspection': 'निरीक्षण फ़ॉर्म भरें',
      'confirm_dispatch': 'प्रेषण स्वीकृति की पुष्टि करें',
      'confirm_dispatch_desc': 'स्वीकार करने पर नागरिक और पंचायत को सूचित किया जाएगा।',
      'confirm_start_nav': 'पुष्टि करें और नेविगेशन शुरू करें',
      'field_inspection_title': 'क्षेत्र निरीक्षण फ़ॉर्म',
      'technical_cause': 'चिह्नित तकनीकी कारण',
      'repair_time': 'अनुमानित मरम्मत समय (घंटे)',
      'materials_required': 'आवश्यक सामग्री',
      'save_inspection': 'निरीक्षण नोट्स सहेजें',
      'upload_before_photo': 'मरम्मत से पहले की फ़ोटो',
      'proceed_completion': 'कार्य पूर्णता पर आगे बढ़ें',
      'upload_after_photo': 'मरम्मत के बाद की फ़ोटो',
      'submit_completion': 'कार्य पूर्णता सबमिट करें',
      'work_completed': 'कार्य पूर्ण हो गया!',
      'work_completed_desc': 'पंचायत प्रशासक को अंतिम सत्यापन के लिए अनुरोध किया गया।',
      'back_to_worker_dashboard': 'वर्कर डैशबोर्ड पर वापस',
      'daily_attendance': 'दैनिक उपस्थिति स्थिति',
      'checked_in_field': 'स्थिति: चेक इन — क्षेत्र में',
      'attendance_time': 'समय: 08:30 AM • GPS स्थान सत्यापित',
      'check_out_today': 'आज चेक आउट करें',
      'admin_console': 'प्रशासनिक नियंत्रण',
      'issue_queue': 'शिकायत सूची',
      'impact_cases': 'प्रभाव मामले',
      'employees': 'कर्मचारी',
      'attendance': 'उपस्थिति',
      'iot_hardware': 'IoT हार्डवेयर',
      'emergency_sos': 'आपातकाल SOS',
      'pending_queue': 'लंबित सूची',
      'critical_ai_alerts': 'गंभीर AI अलर्ट',
      'active_workers': 'सक्रिय कर्मचारी',
      'csr_projects': 'सीएसआर परियोजनाएं',
      'open_sponsorships': 'खुले प्रायोजन',
      'iot_devices': 'IoT उपकरण',
      'gas_anomaly': 'गैस विसंगति अलर्ट',
      'urgent_issues': 'तत्काल शिकायत सूची',
      'see_queue': 'सूची देखें',
      'assign_employee': 'कर्मचारी नियुक्त करें',
      'assign_btn': 'कर्मचारी असाइन करें',
      'verify_field_work': 'पूर्ण क्षेत्र कार्य सत्यापित करें',
      'approve_close': 'स्वीकृत करें और बंद करें',
      'before_after_compare': 'पहले और बाद की तुलना',
      'ai_score': 'AI स्कोर',
      'resolution_rate': 'कुल समाधान दर',
      'avg_resolution': 'औसत समाधान गति',
      'ai_automated': 'AI स्वचालित प्रेषण',
      'user_profile': 'उपयोगकर्ता प्रोफ़ाइल',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'change_language': 'भाषा बदलें',
      'accessibility_settings': 'एक्सेसिबिलिटी सेटिंग',
      'app_settings': 'ऐप सेटिंग',
      'help_support': 'सहायता और समर्थन',
      'about_gramone': 'ग्रामवन के बारे में',
      'sign_out': 'साइन आउट',
      'save_changes': 'परिवर्तन सहेजें',
      'full_name': 'पूरा नाम', 'email': 'ईमेल', 'phone': 'फ़ोन नंबर',
      'welcome_back': 'वापसी पर स्वागत',
      'sign_in_desc': 'अपने पंजीकृत क्रेडेंशियल या मोबाइल नंबर दर्ज करें।',
      'phone_email': 'फ़ोन नंबर या ईमेल', 'password': 'पासवर्ड',
      'forgot_password': 'पासवर्ड भूल गए?', 'sign_in': 'साइन इन',
      'no_account': 'खाता नहीं है? ', 'create_account': 'खाता बनाएं',
      'join_gramone': 'ग्रामवन से जुड़ें',
      'register_desc': 'अपनी नागरिक या प्रशासनिक प्रोफ़ाइल पंजीकृत करें।',
      'mobile_number': 'मोबाइल नंबर', 'panchayat_name': 'ग्राम पंचायत नाम',
      'send_otp': 'OTP सत्यापन भेजें',
      'onboarding1_title': 'नागरिक समस्याएं तुरंत रिपोर्ट करें',
      'onboarding2_title': 'पारदर्शी पंचायत संचालन',
      'onboarding3_title': 'सीएसआर प्रभाव और IoT टेलीमेट्री',
      'skip': 'छोड़ें', 'next': 'अगला', 'get_started': 'शुरू करें',
      'welcome_to_gramone': 'ग्रामवन में आपका स्वागत है',
      'select_role': 'जारी रखने के लिए अपनी भूमिका चुनें।',
      'role_citizen': 'नागरिक', 'role_admin': 'पंचायत प्रशासक',
      'role_block': 'ब्लॉक अधिकारी', 'role_district': 'जिला अधिकारी',
      'role_state': 'राज्य मुख्यालय अधिकारी',
      'role_employee': 'पंचायत क्षेत्र कर्मचारी', 'role_csr': 'सीएसआर भागीदार',
      'select_language': 'भाषा चुनें / Select Language',
      'choose_language': 'अपनी पसंदीदा भाषा चुनें',
      'confirm_language': 'भाषा पुष्टि करें',
      'change_app_language': 'ऐप भाषा बदलें',
      'notifications': 'सूचनाएं',
      'unauthorized_access': 'पहुंच अस्वीकृत',
      'unauthorized_msg': 'आपकी भूमिका को इस स्क्रीन तक पहुंचने की अनुमति नहीं है।',
      'back_to_dashboard': 'डैशबोर्ड पर वापस',
      'offline_banner': 'ऑफलाइन — परिवर्तन ऑनलाइन होने पर स्वचालित रूप से सिंक होंगे',
      'confirm': 'पुष्टि करें', 'cancel': 'रद्द करें',
      'retry': 'पुनः प्रयास करें', 'loading': 'लोड हो रहा है...',
      'no_data': 'कोई डेटा उपलब्ध नहीं', 'error_occurred': 'कुछ गलत हो गया',
      'escalated_cases': 'वृद्धि मामले', 'block_resolution_rate': 'ब्लॉक समाधान दर',
      'panchayat_performance': 'पंचायत प्रदर्शन — इस ब्लॉक में',
      'escalated_awaiting': 'ब्लॉक अनुमोदन प्रतीक्षित मामले',
      'district_label': 'जिला', 'pending_approvals': 'लंबित अनुमोदन',
      'district_csr_fund': 'जिला सीएसआर कोष', 'block_performance': 'ब्लॉक प्रदर्शन रैंकिंग',
      'funding_approvals': 'लंबित वित्त अनुमोदन', 'approve': 'स्वीकृत करें',
      'districts_at_risk': 'जोखिम में जिले', 'district_ranking': 'जिला प्रदर्शन रैंकिंग',
      'export': 'निर्यात', 'policy_mandates': 'सक्रिय नीति आदेश',
      'state_emergency_btn': 'राज्य आपातकालीन नियंत्रण कक्ष खोलें',
      'rate_resolution': 'समाधान गुणवत्ता रेट करें',
      'submit_feedback': 'प्रतिक्रिया सबमिट करें',
    },

    // ── TAMIL ──────────────────────────────────────────────────────────────
    'ta': {
      'app_title': 'கிராம்ஒன்', 'app_tagline': 'குடிமை நிர்வாகம் & சிஎஸ்ஆர் உள்கட்டமைப்பு',
      'citizen_tab': 'முகப்பு', 'my_reports': 'என் புகார்கள்', 'report_issue': 'புகார் செய்',
      'alerts_tab': 'எச்சரிக்கைகள்', 'admin_tab': 'நிர்வாகம்', 'worker_tab': 'என் பணிகள்',
      'csr_tab': 'சிஎஸ்ஆர்', 'projects_tab': 'திட்டங்கள்', 'staff_tab': 'பணியாளர்கள்',
      'queue_tab': 'புகார் வரிசை', 'emergency_tab': 'அவசரநிலை',
      'discover_tab': 'கண்டறி', 'sponsorships_tab': 'நிதியுதவி',
      'block_hq_tab': 'வட்ட தலைமையகம்', 'escalations_tab': 'மேல்முறையீடு',
      'analytics_tab': 'பகுப்பாய்வு', 'district_hq_tab': 'மாவட்ட தலைமையகம்',
      'audit_tab': 'தணிக்கை', 'funding_tab': 'நிதி', 'state_hq_tab': 'மாநில தலைமையகம்',
      'policy_tab': 'கொள்கை', 'disaster_tab': 'பேரிடர்', 'attendance_tab': 'வருகை',
      'work_queue_tab': 'பணி வரிசை', 'profile_tab': 'சுயவிவரம்',
      'citizen_dashboard_title': 'கிராம்ஒன் குடிமகன்',
      'panchayat_dashboard_title': 'பஞ்சாயத்து நிர்வாகி',
      'employee_dashboard_title': 'களப் பணியாளர் போர்டல்',
      'csr_dashboard_title': 'சிஎஸ்ஆர் பங்காளர் மையம்',
      'block_dashboard_title': 'வட்ட அதிகாரி தலைமையகம்',
      'district_dashboard_title': 'மாவட்ட ஆட்சியர் தலைமையகம்',
      'state_dashboard_title': 'மாநில செயலகம்',
      'report_civic_issue': 'குடிமை பிரச்சனையை பதிவு செய்',
      'ai_detect_desc': 'AI தீவிரத்தை கண்டறிந்து அருகிலுள்ள தொழில்நுட்பவியலாளரை நியமிக்கும்.',
      'new_report': 'புதிய அறிக்கை',
      'recent_panchayat_issues': 'சமீபத்திய பஞ்சாயத்து பிரச்சனைகள்',
      'village_projects': 'கிராம திட்டங்கள்',
      'view_all': 'அனைத்தும் காண்க',
      'my_reports_count': 'என் அறிக்கைகள்',
      'resolved': 'தீர்க்கப்பட்டது',
      'active_csr': 'செயலில் சிஎஸ்ஆர்',
      'status_pending': 'நிலுவையில் உள்ளது',
      'status_in_progress': 'செயல்பாட்டில்',
      'status_resolved': 'தீர்க்கப்பட்டது',
      'status_rejected': 'நிராகரிக்கப்பட்டது',
      'status_critical': 'முக்கிய எச்சரிக்கை',
      'cat_water': 'குடிநீர் வழங்கல்',
      'cat_sanitation': 'சுகாதாரம்',
      'cat_roads': 'சாலைகள் & உள்கட்டமைப்பு',
      'cat_electricity': 'மின்சாரம்',
      'cat_environment': 'சுற்றுச்சூழல்',
      'field_worker_portal': 'களப் பணியாளர் போர்டல்',
      'assigned_work': 'நியமிக்கப்பட்ட பணி',
      'tasks': 'பணிகள்', 'high_priority': 'அதிக முன்னுரிமை',
      'completed_tasks': 'முடிக்கப்பட்டது', 'this_month': 'இந்த மாதம்',
      'my_field_assignments': 'என் களப் பணிகள்',
      'assigned_field_work': 'நியமிக்கப்பட்ட களப் பணி',
      'accept_work': 'பணியை ஏற்க', 'fill_inspection': 'ஆய்வு படிவத்தை நிரப்பு',
      'confirm_dispatch': 'அனுப்புதல் ஏற்பை உறுதிப்படுத்து',
      'confirm_dispatch_desc': 'ஏற்பது குடிமகன் மற்றும் பஞ்சாயத்தை அறிவிக்கும்.',
      'confirm_start_nav': 'உறுதிப்படுத்து & வழிகாட்டலைத் தொடங்கு',
      'field_inspection_title': 'கள ஆய்வு படிவம்',
      'technical_cause': 'கண்டறியப்பட்ட தொழில்நுட்ப காரணம்',
      'repair_time': 'மதிப்பிடப்பட்ட சரிசெய்யும் நேரம் (மணிகள்)',
      'materials_required': 'தேவையான பொருட்கள்',
      'save_inspection': 'ஆய்வு குறிப்புகளை சேமி',
      'upload_before_photo': 'சரிசெய்வதற்கு முன் புகைப்படம்',
      'proceed_completion': 'பணி முடிவுக்கு தொடர்',
      'upload_after_photo': 'சரிசெய்த பிறகு புகைப்படம்',
      'submit_completion': 'பணி முடிவை சமர்ப்பி',
      'work_completed': 'பணி முடிந்தது!',
      'work_completed_desc': 'இறுதி சரிபார்ப்புக்காக பஞ்சாயத்து நிர்வாகியிடம் கோரப்பட்டது.',
      'back_to_worker_dashboard': 'பணியாளர் டாஷ்போர்டுக்கு திரும்பு',
      'daily_attendance': 'தினசரி வருகை நிலை',
      'checked_in_field': 'நிலை: சரிபார்க்கப்பட்டது — களத்தில்',
      'attendance_time': 'நேரம்: 08:30 AM • GPS இடம் சரிபார்க்கப்பட்டது',
      'check_out_today': 'இன்று செக் அவுட் செய்',
      'admin_console': 'நிர்வாக கட்டுப்பாடுகள்',
      'issue_queue': 'புகார் வரிசை', 'impact_cases': 'தாக்க வழக்குகள்',
      'employees': 'ஊழியர்கள்', 'attendance': 'வருகை',
      'iot_hardware': 'IoT வன்பொருள்', 'emergency_sos': 'அவசரகால SOS',
      'pending_queue': 'நிலுவையில் உள்ள வரிசை',
      'critical_ai_alerts': 'முக்கிய AI எச்சரிக்கைகள்',
      'active_workers': 'செயலில் உள்ள பணியாளர்கள்',
      'csr_projects': 'சிஎஸ்ஆர் திட்டங்கள்',
      'open_sponsorships': 'திறந்த நிதியுதவிகள்',
      'iot_devices': 'IoT சாதனங்கள்',
      'gas_anomaly': 'வாயு அசாதாரண எச்சரிக்கை',
      'urgent_issues': 'அவசர புகார் வரிசை', 'see_queue': 'வரிசை காண்க',
      'assign_employee': 'பணியாளரை நியமி', 'assign_btn': 'பணியாளரை நியமி',
      'verify_field_work': 'களப் பணியை சரிபார்', 'approve_close': 'அங்கீகரி & மூடு',
      'before_after_compare': 'முன் & பின் ஒப்பீடு', 'ai_score': 'AI மதிப்பெண்',
      'resolution_rate': 'மொத்த தீர்வு விகிதம்', 'avg_resolution': 'சராசரி தீர்வு வேகம்',
      'ai_automated': 'AI தானியங்கி அனுப்புதல்',
      'user_profile': 'பயனர் சுயவிவரம்', 'edit_profile': 'சுயவிவரம் திருத்து',
      'change_language': 'மொழி மாற்று', 'accessibility_settings': 'அணுகல்திறன் அமைப்புகள்',
      'app_settings': 'செயலி அமைப்புகள்', 'help_support': 'உதவி & ஆதரவு',
      'about_gramone': 'கிராம்ஒன் பற்றி', 'sign_out': 'வெளியேறு',
      'save_changes': 'மாற்றங்களை சேமி', 'full_name': 'முழு பெயர்',
      'email': 'மின்னஞ்சல்', 'phone': 'தொலைபேசி எண்',
      'welcome_back': 'மீண்டும் வரவேற்கிறோம்',
      'sign_in_desc': 'உங்கள் பதிவு செய்யப்பட்ட நற்சான்றிதழ்களை உள்ளிடவும்.',
      'phone_email': 'தொலைபேசி எண் அல்லது மின்னஞ்சல்',
      'password': 'கடவுச்சொல்', 'forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'sign_in': 'உள்நுழை', 'no_account': 'கணக்கு இல்லையா? ', 'create_account': 'கணக்கு உருவாக்கு',
      'join_gramone': 'கிராம்ஒன்-ல் சேர்', 'register_desc': 'உங்கள் சுயவிவரத்தை பதிவு செய்யுங்கள்.',
      'mobile_number': 'மொபைல் எண்', 'panchayat_name': 'கிராம பஞ்சாயத்து பெயர்',
      'send_otp': 'OTP சரிபார்ப்பு அனுப்பு',
      'onboarding1_title': 'குடிமை பிரச்சனைகளை உடனே புகாரளி',
      'onboarding2_title': 'வெளிப்படையான பஞ்சாயத்து நடவடிக்கைகள்',
      'onboarding3_title': 'சிஎஸ்ஆர் தாக்கம் & IoT தொலைத்தகவல்',
      'skip': 'தவிர்', 'next': 'அடுத்து', 'get_started': 'தொடங்கு',
      'welcome_to_gramone': 'கிராம்ஒன்-ல் வரவேற்கிறோம்',
      'select_role': 'தொடர உங்கள் பங்கை தேர்ந்தெடுக்கவும்.',
      'role_citizen': 'குடிமகன்', 'role_admin': 'பஞ்சாயத்து நிர்வாகி',
      'role_block': 'வட்ட அதிகாரி', 'role_district': 'மாவட்ட அதிகாரி',
      'role_state': 'மாநில முதன்மையக அதிகாரி',
      'role_employee': 'பஞ்சாயத்து களப் பணியாளர்', 'role_csr': 'சிஎஸ்ஆர் பங்காளர்',
      'select_language': 'மொழி தேர்ந்தெடு / Select Language',
      'choose_language': 'உங்கள் விருப்பமான மொழியை தேர்ந்தெடுக்கவும்',
      'confirm_language': 'மொழியை உறுதிப்படுத்து', 'change_app_language': 'செயலி மொழி மாற்று',
      'notifications': 'அறிவிப்புகள்',
      'unauthorized_access': 'அணுகல் மறுக்கப்பட்டது',
      'unauthorized_msg': 'இந்த திரையை அணுக உங்களுக்கு அனுமதி இல்லை.',
      'back_to_dashboard': 'டாஷ்போர்டுக்கு திரும்பு',
      'offline_banner': 'ஆஃப்லைன் — ஆன்லைன் ஆகும்போது மாற்றங்கள் தானாக ஒத்திசைக்கப்படும்',
      'confirm': 'உறுதிப்படுத்து', 'cancel': 'ரத்து செய்', 'retry': 'மீண்டும் முயற்சி',
      'loading': 'ஏற்றுகிறது...', 'no_data': 'தரவு இல்லை', 'error_occurred': 'பிழை ஏற்பட்டது',
      'escalated_cases': 'மேல்முறையீட்டு வழக்குகள்',
      'block_resolution_rate': 'வட்ட தீர்வு விகிதம்',
      'panchayat_performance': 'பஞ்சாயத்து செயல்திறன் — இந்த வட்டம்',
      'escalated_awaiting': 'வட்ட அங்கீகாரம் காத்திருக்கும் வழக்குகள்',
      'pending_approvals': 'நிலுவையில் உள்ள அங்கீகாரங்கள்',
      'district_csr_fund': 'மாவட்ட சிஎஸ்ஆர் நிதி',
      'block_performance': 'வட்ட செயல்திறன் தரவரிசை',
      'funding_approvals': 'நிலுவையில் உள்ள நிதி அங்கீகாரங்கள்',
      'approve': 'அங்கீகரி', 'districts_at_risk': 'ஆபத்தில் உள்ள மாவட்டங்கள்',
      'district_ranking': 'மாவட்ட செயல்திறன் தரவரிசை',
      'export': 'ஏற்றுமதி', 'policy_mandates': 'செயலில் உள்ள கொள்கை ஆணைகள்',
      'state_emergency_btn': 'மாநில அவசரகால கட்டுப்பாட்டு அறையை திற',
      'rate_resolution': 'தீர்வு தரத்தை மதிப்பிடு', 'submit_feedback': 'கருத்தை சமர்ப்பி',
    },

    // ── TELUGU ─────────────────────────────────────────────────────────────
    'te': {
      'app_title': 'గ్రామ్‌వన్', 'app_tagline': 'పౌర పాలన & CSR మౌలిక సదుపాయాలు',
      'citizen_tab': 'హోమ్', 'my_reports': 'నా ఫిర్యాదులు', 'report_issue': 'ఫిర్యాదు',
      'alerts_tab': 'అలర్టులు', 'admin_tab': 'అడ్మిన్', 'worker_tab': 'నా పనులు',
      'csr_tab': 'సిఎస్ఆర్', 'projects_tab': 'ప్రాజెక్టులు', 'staff_tab': 'సిబ్బంది',
      'queue_tab': 'ఫిర్యాదు క్యూ', 'emergency_tab': 'అత్యవసరం',
      'citizen_dashboard_title': 'గ్రామ్‌వన్ పౌరుడు',
      'panchayat_dashboard_title': 'పంచాయతీ అడ్మిన్ కన్సోల్',
      'employee_dashboard_title': 'ఫీల్డ్ వర్కర్ పోర్టల్',
      'status_pending': 'పెండింగ్ ట్రయాజ్',
      'status_in_progress': 'పురోగతిలో ఉంది',
      'status_resolved': 'పరిష్కరించబడింది',
      'status_rejected': 'తిరస్కరించబడింది',
      'status_critical': 'అత్యవసర హెచ్చరిక',
      'cat_water': 'నీటి సరఫరా', 'cat_sanitation': 'పారిశుద్ధ్యం',
      'cat_roads': 'రోడ్లు & మౌలిక సదుపాయాలు', 'cat_electricity': 'విద్యుత్',
      'cat_environment': 'పర్యావరణం',
      'view_all': 'అన్నీ చూడు', 'report_civic_issue': 'పౌర సమస్యను నివేదించు',
      'new_report': 'కొత్త నివేదిక', 'recent_panchayat_issues': 'ఇటీవలి పంచాయతీ సమస్యలు',
      'village_projects': 'గ్రామ ప్రాజెక్టులు',
      'field_worker_portal': 'ఫీల్డ్ వర్కర్ పోర్టల్',
      'assigned_work': 'కేటాయించిన పని', 'tasks': 'పనులు', 'high_priority': 'అధిక ప్రాధాన్యత',
      'completed_tasks': 'పూర్తయింది', 'this_month': 'ఈ నెల',
      'my_field_assignments': 'నా ఫీల్డ్ అసైన్‌మెంట్‌లు',
      'assigned_field_work': 'కేటాయించిన ఫీల్డ్ పని',
      'accept_work': 'పనిని స్వీకరించు', 'fill_inspection': 'తనిఖీ ఫారం నింపు',
      'confirm_dispatch': 'డిస్పాచ్ ఆమోదాన్ని ధృవీకరించు',
      'confirm_start_nav': 'ధృవీకరించు & నావిగేషన్ ప్రారంభించు',
      'field_inspection_title': 'ఫీల్డ్ తనిఖీ ఫారం',
      'technical_cause': 'గుర్తించిన సాంకేతిక కారణం',
      'repair_time': 'అంచనా మరమ్మత్తు సమయం (గంటలు)',
      'materials_required': 'అవసరమైన సామగ్రి',
      'save_inspection': 'తనిఖీ నోట్స్ సేవ్ చేయి',
      'upload_before_photo': 'మరమ్మత్తుకు ముందు ఫోటో',
      'proceed_completion': 'పని పూర్తికి కొనసాగు',
      'upload_after_photo': 'మరమ్మత్తు తర్వాత ఫోటో',
      'submit_completion': 'పని పూర్తిని సబ్మిట్ చేయి',
      'work_completed': 'పని పూర్తయింది!',
      'work_completed_desc': 'పంచాయతీ అడ్మిన్ తుది ధృవీకరణ కోసం అభ్యర్థించారు.',
      'back_to_worker_dashboard': 'వర్కర్ డాష్‌బోర్డ్‌కు తిరిగి',
      'daily_attendance': 'రోజువారీ హాజరు స్థితి',
      'checked_in_field': 'స్థితి: చెక్ ఇన్ — ఫీల్డ్‌లో',
      'attendance_time': 'సమయం: 08:30 AM • GPS స్థానం ధృవీకరించబడింది',
      'check_out_today': 'ఈరోజు చెక్ అవుట్ చేయి',
      'sign_out': 'సైన్ అవుట్', 'save_changes': 'మార్పులు సేవ్ చేయి',
      'welcome_back': 'తిరిగి స్వాగతం', 'sign_in': 'సైన్ ఇన్',
      'forgot_password': 'పాస్‌వర్డ్ మర్చిపోయారా?', 'password': 'పాస్‌వర్డ్',
      'select_language': 'భాష ఎంచుకో / Select Language',
      'choose_language': 'మీకు నచ్చిన భాష ఎంచుకోండి',
      'confirm_language': 'భాషను ధృవీకరించు', 'change_app_language': 'యాప్ భాష మార్చు',
      'notifications': 'నోటిఫికేషన్లు',
      'unauthorized_access': 'అనుమతి నిరాకరించబడింది',
      'unauthorized_msg': 'మీకు ఈ స్క్రీన్‌కు యాక్సెస్ అనుమతి లేదు.',
      'back_to_dashboard': 'డాష్‌బోర్డ్‌కు తిరిగి',
      'offline_banner': 'ఆఫ్‌లైన్ — ఆన్‌లైన్ అయినప్పుడు మార్పులు స్వయంచాలకంగా సమకాలీకరించబడతాయి',
      'confirm': 'ధృవీకరించు', 'cancel': 'రద్దు చేయి', 'retry': 'మళ్ళీ ప్రయత్నించు',
      'loading': 'లోడ్ అవుతోంది...', 'no_data': 'డేటా అందుబాటులో లేదు',
      'error_occurred': 'ఏదో తప్పు జరిగింది',
      'skip': 'వదిలు', 'next': 'తదుపరి', 'get_started': 'ప్రారంభించు',
      'welcome_to_gramone': 'గ్రామ్‌వన్‌కు స్వాగతం',
      'select_role': 'కొనసాగించడానికి మీ పాత్రను ఎంచుకోండి.',
      'admin_console': 'పరిపాలనా నియంత్రణలు',
      'issue_queue': 'ఫిర్యాదు క్యూ', 'employees': 'ఉద్యోగులు', 'attendance': 'హాజరు',
      'approve_close': 'ఆమోదించు & మూసివేయి', 'approve': 'ఆమోదించు',
    },

    // ── KANNADA ────────────────────────────────────────────────────────────
    'kn': {
      'app_title': 'ಗ್ರಾಮ್‌ಒನ್', 'citizen_tab': 'ಮನೆ', 'my_reports': 'ನನ್ನ ದೂರುಗಳು',
      'report_issue': 'ದೂರು ನೀಡಿ', 'alerts_tab': 'ಎಚ್ಚರಿಕೆಗಳು', 'admin_tab': 'ಆಡಳಿತ',
      'worker_tab': 'ನನ್ನ ಕಾರ್ಯಗಳು', 'status_pending': 'ಬಾಕಿ ತ್ರಿಯಾಜ್',
      'status_in_progress': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ', 'status_resolved': 'ಪರಿಹರಿಸಲಾಗಿದೆ',
      'status_rejected': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ', 'status_critical': 'ತುರ್ತು ಎಚ್ಚರಿಕೆ',
      'cat_water': 'ನೀರು ಸರಬರಾಜು', 'cat_sanitation': 'ನೈರ್ಮಲ್ಯ',
      'cat_roads': 'ರಸ್ತೆಗಳು & ಮೂಲಸೌಕರ್ಯ', 'cat_electricity': 'ವಿದ್ಯುತ್',
      'cat_environment': 'ಪರಿಸರ', 'view_all': 'ಎಲ್ಲ ನೋಡಿ',
      'field_worker_portal': 'ಕ್ಷೇತ್ರ ಕಾರ್ಯಕರ್ತ ಪೋರ್ಟಲ್',
      'assigned_work': 'ನಿಯೋಜಿಸಲಾದ ಕಾರ್ಯ', 'tasks': 'ಕಾರ್ಯಗಳು',
      'completed_tasks': 'ಪೂರ್ಣಗೊಂಡಿದೆ', 'my_field_assignments': 'ನನ್ನ ಕ್ಷೇತ್ರ ನಿಯೋಜನೆಗಳು',
      'sign_out': 'ಸೈನ್ ಔಟ್', 'welcome_back': 'ಮತ್ತೆ ಸ್ವಾಗತ',
      'sign_in': 'ಸೈನ್ ಇನ್', 'password': 'ಪಾಸ್‌ವರ್ಡ್',
      'select_language': 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ / Select Language',
      'choose_language': 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'confirm_language': 'ಭಾಷೆ ದೃಢೀಕರಿಸಿ', 'change_app_language': 'ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ ಬದಲಾಯಿಸಿ',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'unauthorized_access': 'ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ',
      'unauthorized_msg': 'ಈ ಪರದೆಯನ್ನು ಪ್ರವೇಶಿಸಲು ನಿಮಗೆ ಅನುಮತಿಯಿಲ್ಲ.',
      'back_to_dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ',
      'skip': 'ಬಿಡಿ', 'next': 'ಮುಂದೆ', 'get_started': 'ಪ್ರಾರಂಭಿಸಿ',
      'confirm': 'ದೃಢೀಕರಿಸಿ', 'cancel': 'ರದ್ದು ಮಾಡಿ', 'save_changes': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    },

    // ── MALAYALAM ──────────────────────────────────────────────────────────
    'ml': {
      'app_title': 'ഗ്രാംവൺ', 'app_tagline': 'പൗര ഭരണം & CSR അടിസ്ഥാന സൗകര്യം',
      'citizen_tab': 'ഹോം', 'my_reports': 'എന്റെ പരാതികൾ', 'report_issue': 'പരാതി',
      'alerts_tab': 'അലേർട്ടുകൾ', 'admin_tab': 'അഡ്മിൻ', 'worker_tab': 'എന്റെ ജോലികൾ',
      'csr_tab': 'സിഎസ്ആർ', 'projects_tab': 'പ്രൊജക്ടുകൾ', 'staff_tab': 'ജീവനക്കാർ',
      'queue_tab': 'പരാതി ക്യൂ', 'emergency_tab': 'അടിയന്തരം',
      'citizen_dashboard_title': 'ഗ്രാംവൺ പൗരൻ',
      'panchayat_dashboard_title': 'പഞ്ചായത്ത് അഡ്മിൻ കൺസോൾ',
      'employee_dashboard_title': 'ഫീൽഡ് വർക്കർ പോർട്ടൽ',
      'status_pending': 'തീർപ്പ് കൽപ്പിക്കേണ്ടത്',
      'status_in_progress': 'നടന്നുകൊണ്ടിരിക്കുന്നു',
      'status_resolved': 'പരിഹരിച്ചു', 'status_rejected': 'നിരസിച്ചു',
      'status_critical': 'അടിയന്തര അലേർട്ട്',
      'cat_water': 'ജലവിതരണം', 'cat_sanitation': 'ശുചിത്വം',
      'cat_roads': 'റോഡുകൾ & അടിസ്ഥാനസൗകര്യം', 'cat_electricity': 'വൈദ്യുതി',
      'cat_environment': 'പരിസ്ഥിതി', 'view_all': 'എല്ലാം കാണൂ',
      'report_civic_issue': 'പൗര പ്രശ്നം റിപ്പോർട്ട് ചെയ്യൂ',
      'new_report': 'പുതിയ റിപ്പോർട്ട്',
      'recent_panchayat_issues': 'സമീപകാല പഞ്ചായത്ത് പ്രശ്നങ്ങൾ',
      'village_projects': 'ഗ്രാമ പദ്ധതികൾ',
      'field_worker_portal': 'ഫീൽഡ് വർക്കർ പോർട്ടൽ',
      'assigned_work': 'നിയോഗിക്കപ്പെട്ട ജോലി', 'tasks': 'ജോലികൾ',
      'high_priority': 'ഉയർന്ന മുൻഗണന', 'completed_tasks': 'പൂർത്തിയായി',
      'this_month': 'ഈ മാസം', 'my_field_assignments': 'എന്റെ ഫീൽഡ് ഡ്യൂട്ടികൾ',
      'assigned_field_work': 'നിയോഗിക്കപ്പെട്ട ഫീൽഡ് ജോലി',
      'accept_work': 'ജോലി സ്വീകരിക്കൂ', 'fill_inspection': 'പരിശോധന ഫോം പൂരിപ്പിക്കൂ',
      'confirm_dispatch': 'അയക്കൽ സ്വീകൃതി സ്ഥിരീകരിക്കൂ',
      'confirm_dispatch_desc': 'സ്വീകരിക്കുമ്പോൾ പൗരരനേയും പഞ്ചായത്തിനേയും അറിയിക്കും.',
      'confirm_start_nav': 'സ്ഥിരീകരിക്കൂ & നാവിഗേഷൻ ആരംഭിക്കൂ',
      'field_inspection_title': 'ഫീൽഡ് പരിശോധന ഫോം',
      'technical_cause': 'കണ്ടെത്തിയ സാങ്കേതിക കാരണം',
      'repair_time': 'കണക്കാക്കിയ അറ്റകുറ്റ സമയം (മണിക്കൂർ)',
      'materials_required': 'ആവശ്യമായ സാമഗ്രികൾ',
      'save_inspection': 'പരിശോധന കുറിപ്പുകൾ സേവ് ചെയ്യൂ',
      'upload_before_photo': 'അറ്റകുറ്റ ജോലിക്ക് മുൻപ് ഫോട്ടോ',
      'proceed_completion': 'ജോലി പൂർത്തിക്ക് തുടരൂ',
      'upload_after_photo': 'അറ്റകുറ്റ ജോലിക്ക് ശേഷം ഫോട്ടോ',
      'submit_completion': 'ജോലി പൂർത്തി സമർപ്പിക്കൂ',
      'work_completed': 'ജോലി പൂർത്തിയായി!',
      'work_completed_desc': 'അന്തിമ പരിശോധനക്ക് പഞ്ചായത്ത് അഡ്മിനോട് അഭ്യർത്ഥിച്ചു.',
      'back_to_worker_dashboard': 'വർക്കർ ഡാഷ്‌ബോർഡിലേക്ക് മടങ്ങൂ',
      'daily_attendance': 'ദൈനംദിന ഹാജർ നില',
      'checked_in_field': 'നില: ചെക്ക് ഇൻ — ഫീൽഡിൽ',
      'attendance_time': 'സമയം: 08:30 AM • GPS സ്ഥാനം സ്ഥിരീകരിച്ചു',
      'check_out_today': 'ഇന്ന് ചെക്ക് ഔട്ട് ചെയ്യൂ',
      'admin_console': 'ഭരണ നിയന്ത്രണങ്ങൾ', 'issue_queue': 'പരാതി ക്യൂ',
      'employees': 'ജീവനക്കാർ', 'attendance': 'ഹാജർ',
      'emergency_sos': 'അടിയന്തര SOS', 'approve_close': 'അംഗീകരിക്കൂ & അടക്കൂ',
      'user_profile': 'ഉപയോക്തൃ പ്രൊഫൈൽ', 'edit_profile': 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യൂ',
      'change_language': 'ഭാഷ മാറ്റൂ', 'accessibility_settings': 'ആക്സസിബിലിറ്റി ക്രമീകരണങ്ങൾ',
      'app_settings': 'ആപ്പ് ക്രമീകരണങ്ങൾ', 'help_support': 'സഹായം & പിന്തുണ',
      'about_gramone': 'ഗ്രാംവൺ പറ്റി', 'sign_out': 'സൈൻ ഔട്ട്',
      'save_changes': 'മാറ്റങ്ങൾ സേവ് ചെയ്യൂ', 'full_name': 'പൂർണ്ണ നാമം',
      'email': 'ഇ-മെയിൽ', 'phone': 'ഫോൺ നമ്പർ',
      'welcome_back': 'സ്വാഗതം', 'sign_in': 'സൈൻ ഇൻ',
      'forgot_password': 'പാസ്‌വേർഡ് മറന്നോ?', 'password': 'പാസ്‌വേർഡ്',
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കൂ / Select Language',
      'choose_language': 'നിങ്ങൾ ഇഷ്ടപ്പെടുന്ന ഭാഷ തിരഞ്ഞെടുക്കൂ',
      'confirm_language': 'ഭാഷ സ്ഥിരീകരിക്കൂ', 'change_app_language': 'ആപ്പ് ഭാഷ മാറ്റൂ',
      'notifications': 'അറിയിപ്പുകൾ',
      'unauthorized_access': 'ആക്സസ് നിഷേധിക്കപ്പെട്ടു',
      'unauthorized_msg': 'ഈ സ്‌ക്രീൻ കാണാൻ നിങ്ങൾക്ക് അനുമതിയില്ല.',
      'back_to_dashboard': 'ഡാഷ്‌ബോർഡിലേക്ക് മടങ്ങൂ',
      'offline_banner': 'ഓഫ്‌ലൈൻ — ഓൺലൈൻ ആകുമ്പോൾ മാറ്റങ്ങൾ സ്വയം സമന്വയിക്കും',
      'skip': 'ഒഴിവാക്കൂ', 'next': 'അടുത്തത്', 'get_started': 'ആരംഭിക്കൂ',
      'welcome_to_gramone': 'ഗ്രാംവൺ-ലേക്ക് സ്വാഗതം',
      'select_role': 'തുടരാൻ നിങ്ങളുടെ റോൾ തിരഞ്ഞെടുക്കൂ.',
      'confirm': 'സ്ഥിരീകരിക്കൂ', 'cancel': 'റദ്ദ് ചെയ്യൂ', 'retry': 'വീണ്ടും ശ്രമിക്കൂ',
      'loading': 'ലോഡ് ചെയ്യുന്നു...', 'no_data': 'ഡാറ്റ ലഭ്യമല്ല',
      'error_occurred': 'എന്തോ തെറ്റ് സംഭവിച്ചു',
      'approve': 'അംഗീകരിക്കൂ',
    },

    // ── MARATHI ────────────────────────────────────────────────────────────
    'mr': {
      'app_title': 'ग्रामवन', 'citizen_tab': 'मुख्यपृष्ठ', 'my_reports': 'माझ्या तक्रारी',
      'report_issue': 'तक्रार नोंदवा', 'alerts_tab': 'सूचना', 'admin_tab': 'प्रशासन',
      'worker_tab': 'माझी कामे', 'status_pending': 'प्रलंबित',
      'status_in_progress': 'प्रगतीत', 'status_resolved': 'निराकरण झाले',
      'status_rejected': 'नाकारले', 'status_critical': 'गंभीर सूचना',
      'cat_water': 'जलपुरवठा', 'cat_sanitation': 'स्वच्छता',
      'cat_roads': 'रस्ते व पायाभूत सुविधा', 'cat_electricity': 'वीज',
      'cat_environment': 'पर्यावरण', 'view_all': 'सर्व पहा',
      'field_worker_portal': 'क्षेत्र कार्यकर्ता पोर्टल',
      'assigned_work': 'नियुक्त काम', 'tasks': 'कामे', 'completed_tasks': 'पूर्ण',
      'my_field_assignments': 'माझी क्षेत्र नियुक्ती', 'sign_out': 'साइन आउट',
      'welcome_back': 'परत स्वागत', 'sign_in': 'साइन इन', 'password': 'पासवर्ड',
      'select_language': 'भाषा निवडा / Select Language',
      'choose_language': 'तुमची पसंतीची भाषा निवडा',
      'confirm_language': 'भाषा पुष्टी करा', 'change_app_language': 'अॅप भाषा बदला',
      'notifications': 'सूचना', 'unauthorized_access': 'प्रवेश नाकारला',
      'unauthorized_msg': 'या स्क्रीनवर प्रवेश करण्याची परवानगी नाही.',
      'back_to_dashboard': 'डॅशबोर्डवर परत', 'skip': 'वगळा', 'next': 'पुढे',
      'get_started': 'सुरू करा', 'confirm': 'पुष्टी करा', 'cancel': 'रद्द करा',
      'save_changes': 'बदल जतन करा',
    },

    // ── BENGALI ────────────────────────────────────────────────────────────
    'bn': {
      'app_title': 'গ্রামওয়ান', 'citizen_tab': 'হোম', 'my_reports': 'আমার অভিযোগ',
      'report_issue': 'অভিযোগ করুন', 'alerts_tab': 'সতর্কতা', 'admin_tab': 'প্রশাসন',
      'worker_tab': 'আমার কাজ', 'status_pending': 'অপেক্ষারত',
      'status_in_progress': 'চলমান', 'status_resolved': 'সমাধান হয়েছে',
      'status_rejected': 'প্রত্যাখ্যাত', 'status_critical': 'জরুরি সতর্কতা',
      'cat_water': 'জল সরবরাহ', 'cat_sanitation': 'স্যানিটেশন',
      'cat_roads': 'রাস্তা ও অবকাঠামো', 'cat_electricity': 'বিদ্যুৎ',
      'cat_environment': 'পরিবেশ', 'view_all': 'সব দেখুন',
      'field_worker_portal': 'ফিল্ড ওয়ার্কার পোর্টাল',
      'assigned_work': 'নির্ধারিত কাজ', 'tasks': 'কাজ', 'completed_tasks': 'সম্পন্ন',
      'my_field_assignments': 'আমার ফিল্ড কাজ', 'sign_out': 'সাইন আউট',
      'welcome_back': 'আবার স্বাগতম', 'sign_in': 'সাইন ইন', 'password': 'পাসওয়ার্ড',
      'select_language': 'ভাষা বেছে নিন / Select Language',
      'choose_language': 'আপনার পছন্দের ভাষা বেছে নিন',
      'confirm_language': 'ভাষা নিশ্চিত করুন', 'change_app_language': 'অ্যাপ ভাষা পরিবর্তন করুন',
      'notifications': 'বিজ্ঞপ্তি', 'unauthorized_access': 'প্রবেশ অস্বীকৃত',
      'unauthorized_msg': 'এই স্ক্রিনে প্রবেশের অনুমতি নেই।',
      'back_to_dashboard': 'ড্যাশবোর্ডে ফিরুন', 'skip': 'এড়িয়ে যান',
      'next': 'পরবর্তী', 'get_started': 'শুরু করুন',
      'confirm': 'নিশ্চিত করুন', 'cancel': 'বাতিল', 'save_changes': 'পরিবর্তন সংরক্ষণ করুন',
    },

    // ── GUJARATI ───────────────────────────────────────────────────────────
    'gu': {
      'app_title': 'ગ્રામવન', 'citizen_tab': 'હોમ', 'my_reports': 'મારી ફરિયાદો',
      'report_issue': 'ફરિયાદ', 'alerts_tab': 'ચેતવણી', 'admin_tab': 'વહીવટ',
      'worker_tab': 'મારા કામ', 'status_pending': 'બાકી',
      'status_in_progress': 'પ્રગતિ પર', 'status_resolved': 'ઉકેલ થયો',
      'status_rejected': 'નકારવામાં', 'status_critical': 'ગંભીર ચેતવણી',
      'cat_water': 'પાણી પુરવઠો', 'cat_sanitation': 'સ્વચ્છતા',
      'cat_roads': 'રસ્તા અને ઈન્ફ્રાસ્ટ્રક્ચર', 'cat_electricity': 'વીજળી',
      'cat_environment': 'પર્યાવરણ', 'view_all': 'બધા જુઓ',
      'field_worker_portal': 'ફીલ્ડ વર્કર પોર્ટલ', 'assigned_work': 'સોંપાયેલ કામ',
      'tasks': 'કામ', 'completed_tasks': 'પૂર્ણ', 'my_field_assignments': 'મારી ફીલ્ડ ફરજ',
      'sign_out': 'સાઇન આઉટ', 'welcome_back': 'ફરી સ્વાગત',
      'sign_in': 'સાઇન ઇન', 'password': 'પાસવર્ડ',
      'select_language': 'ભાષા પસંદ કરો / Select Language',
      'choose_language': 'તમારી પ્રિય ભાષા પસંદ કરો',
      'confirm_language': 'ભાષા ખાતરી કરો', 'change_app_language': 'ઍપ ભાષા બદલો',
      'notifications': 'સૂચનાઓ', 'unauthorized_access': 'પ્રવેશ નકારવામાં',
      'unauthorized_msg': 'આ સ્ક્રીન ઍક્સેસ કરવાની પરવાનગી નથી.',
      'back_to_dashboard': 'ડૅશબોર્ડ પર પાછા', 'skip': 'આગળ', 'next': 'આગળ',
      'get_started': 'શરૂ કરો', 'confirm': 'ખાતરી', 'cancel': 'રદ',
      'save_changes': 'ફેરફારો સાચવો',
    },

    // ── PUNJABI ────────────────────────────────────────────────────────────
    'pa': {
      'app_title': 'ਗ੍ਰਾਮਵਨ', 'citizen_tab': 'ਹੋਮ', 'my_reports': 'ਮੇਰੀਆਂ ਸ਼ਿਕਾਇਤਾਂ',
      'report_issue': 'ਸ਼ਿਕਾਇਤ', 'alerts_tab': 'ਚੇਤਾਵਨੀਆਂ', 'admin_tab': 'ਪ੍ਰਸ਼ਾਸਨ',
      'worker_tab': 'ਮੇਰੇ ਕੰਮ', 'status_pending': 'ਲੰਬਿਤ',
      'status_in_progress': 'ਚੱਲ ਰਿਹਾ', 'status_resolved': 'ਹੱਲ ਹੋਇਆ',
      'status_rejected': 'ਰੱਦ', 'status_critical': 'ਗੰਭੀਰ ਚੇਤਾਵਨੀ',
      'cat_water': 'ਪਾਣੀ ਸਪਲਾਈ', 'cat_sanitation': 'ਸਫ਼ਾਈ',
      'cat_roads': 'ਸੜਕਾਂ ਅਤੇ ਬੁਨਿਆਦੀ ਢਾਂਚਾ', 'cat_electricity': 'ਬਿਜਲੀ',
      'cat_environment': 'ਵਾਤਾਵਰਣ', 'view_all': 'ਸਭ ਦੇਖੋ',
      'field_worker_portal': 'ਖੇਤਰ ਕਾਰਕੁਨ ਪੋਰਟਲ', 'assigned_work': 'ਸੌਂਪੇ ਕੰਮ',
      'tasks': 'ਕੰਮ', 'completed_tasks': 'ਮੁਕੰਮਲ', 'my_field_assignments': 'ਮੇਰੇ ਖੇਤਰ ਕੰਮ',
      'sign_out': 'ਸਾਈਨ ਆਊਟ', 'welcome_back': 'ਦੁਬਾਰਾ ਜੀ ਆਇਆਂ',
      'sign_in': 'ਸਾਈਨ ਇਨ', 'password': 'ਪਾਸਵਰਡ',
      'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ / Select Language',
      'choose_language': 'ਆਪਣੀ ਮਨਪਸੰਦ ਭਾਸ਼ਾ ਚੁਣੋ',
      'confirm_language': 'ਭਾਸ਼ਾ ਪੁਸ਼ਟੀ ਕਰੋ', 'change_app_language': 'ਐਪ ਭਾਸ਼ਾ ਬਦਲੋ',
      'notifications': 'ਸੂਚਨਾਵਾਂ', 'unauthorized_access': 'ਪਹੁੰਚ ਰੱਦ',
      'unauthorized_msg': 'ਇਸ ਸਕ੍ਰੀਨ ਤੱਕ ਪਹੁੰਚਣ ਦੀ ਆਗਿਆ ਨਹੀਂ।',
      'back_to_dashboard': 'ਡੈਸ਼ਬੋਰਡ ਤੇ ਵਾਪਸ', 'skip': 'ਛੱਡੋ', 'next': 'ਅਗਲਾ',
      'get_started': 'ਸ਼ੁਰੂ ਕਰੋ', 'confirm': 'ਪੁਸ਼ਟੀ', 'cancel': 'ਰੱਦ',
      'save_changes': 'ਬਦਲਾਅ ਸੁਰੱਖਿਅਤ ਕਰੋ',
    },

    // ── ODIA ───────────────────────────────────────────────────────────────
    'od': {
      'app_title': 'ଗ୍ରାମ୍‌ଓ୍ଵାନ', 'citizen_tab': 'ହୋମ', 'my_reports': 'ମୋ ଅଭିଯୋଗ',
      'report_issue': 'ଅଭିଯୋଗ', 'alerts_tab': 'ସତର୍କତା', 'worker_tab': 'ମୋ କାମ',
      'status_pending': 'ଅପ୍ରତ୍ୟାଶିତ', 'status_in_progress': 'ଚାଲୁ',
      'status_resolved': 'ସମାଧାନ', 'status_rejected': 'ପ୍ରତ୍ୟାଖ୍ୟାନ',
      'status_critical': 'ଜରୁରୀ ସତର୍କତା',
      'cat_water': 'ଜଳ ଯୋଗାଣ', 'cat_sanitation': 'ସ୍ୱଚ୍ଛତା',
      'cat_electricity': 'ବିଦ୍ୟୁତ', 'cat_environment': 'ପରିବେଶ',
      'view_all': 'ସବୁ ଦେଖ', 'field_worker_portal': 'ଫିଲ୍ଡ ୱର୍କର ପୋର୍ଟାଲ',
      'assigned_work': 'ନ୍ୟସ୍ତ କାମ', 'tasks': 'କାମ', 'completed_tasks': 'ସମ୍ପୂର୍ଣ',
      'sign_out': 'ସାଇନ ଆଉଟ', 'welcome_back': 'ପୁଣି ସ୍ୱାଗତ',
      'sign_in': 'ସାଇନ ଇନ', 'password': 'ପାସୱାର୍ଡ',
      'select_language': 'ଭାଷା ବାଛ / Select Language',
      'choose_language': 'ଆପଣଙ୍କ ପସନ୍ଦର ଭାଷା ବାଛ',
      'confirm_language': 'ଭାଷା ନିଶ୍ଚିତ', 'change_app_language': 'ଆପ ଭାଷା ବଦଳ',
      'notifications': 'ବିଜ୍ଞପ୍ତି', 'unauthorized_access': 'ପ୍ରବେଶ ଅସ୍ୱୀକୃତ',
      'unauthorized_msg': 'ଏହି ସ୍କ୍ରିନ୍ ଦେଖିବାର ଅନୁମତି ନାହିଁ।',
      'back_to_dashboard': 'ଡ୍ୟାସବୋର୍ଡ ଫେରନ୍ତୁ', 'skip': 'ଛାଡ଼ :', 'next': 'ପରବର୍ତ୍ତୀ',
      'get_started': 'ଆରଂଭ', 'confirm': 'ନିଶ୍ଚିତ', 'cancel': 'ବାତିଲ',
      'save_changes': 'ପରିବର୍ତ୍ତନ ସଂରକ୍ଷଣ',
    },

    // ── ASSAMESE ───────────────────────────────────────────────────────────
    'as': {
      'app_title': 'গ্ৰামৱান', 'citizen_tab': 'হোম', 'my_reports': 'মোৰ অভিযোগ',
      'report_issue': 'অভিযোগ', 'alerts_tab': 'সতৰ্কতা', 'worker_tab': 'মোৰ কাম',
      'status_pending': 'বিচাৰাধীন', 'status_in_progress': 'চলি আছে',
      'status_resolved': 'সমাধান হৈছে', 'status_rejected': 'প্ৰত্যাখ্যান',
      'status_critical': 'জৰুৰী সতৰ্কতা',
      'cat_water': 'পানী যোগান', 'cat_sanitation': 'পৰিষ্কাৰ-পৰিচ্ছন্নতা',
      'cat_electricity': 'বিদ্যুৎ', 'cat_environment': 'পৰিৱেশ',
      'view_all': 'সকলো চাওক', 'field_worker_portal': 'ফিল্ড ৱৰ্কাৰ পৰ্টেল',
      'assigned_work': 'নিযুক্ত কাম', 'tasks': 'কাম', 'completed_tasks': 'সম্পূৰ্ণ',
      'sign_out': 'চাইন আউট', 'welcome_back': 'পুনৰ স্বাগতম',
      'sign_in': 'চাইন ইন', 'password': 'পাছৱৰ্ড',
      'select_language': 'ভাষা বাছক / Select Language',
      'choose_language': 'আপোনাৰ পছন্দৰ ভাষা বাছক',
      'confirm_language': 'ভাষা নিশ্চিত কৰক', 'change_app_language': 'এপ্‌ ভাষা সলনি কৰক',
      'notifications': 'জাননী', 'unauthorized_access': 'প্ৰৱেশ অস্বীকৃত',
      'unauthorized_msg': 'এই স্ক্ৰিন চাবলৈ অনুমতি নাই।',
      'back_to_dashboard': 'ড্যাশবোৰ্ডলৈ যাওক', 'skip': 'এৰক', 'next': 'পৰৱৰ্তী',
      'get_started': 'আৰম্ভ কৰক', 'confirm': 'নিশ্চিত', 'cancel': 'বাতিল',
      'save_changes': 'পৰিবৰ্তন সংৰক্ষণ',
    },

    // ── URDU (RTL) ─────────────────────────────────────────────────────────
    'ur': {
      'app_title': 'گرام ون', 'app_tagline': 'شہری حکمرانی اور سی ایس آر بنیادی ڈھانچہ',
      'citizen_tab': 'ہوم', 'my_reports': 'میری شکایات', 'report_issue': 'شکایت',
      'alerts_tab': 'انتباہات', 'admin_tab': 'انتظامیہ', 'worker_tab': 'میرے کام',
      'csr_tab': 'سی ایس آر', 'projects_tab': 'منصوبے', 'staff_tab': 'عملہ',
      'queue_tab': 'شکایت قطار', 'emergency_tab': 'ہنگامی',
      'citizen_dashboard_title': 'گرام ون شہری',
      'panchayat_dashboard_title': 'پنچایت ایڈمن',
      'employee_dashboard_title': 'فیلڈ ورکر پورٹل',
      'status_pending': 'زیر التوا',
      'status_in_progress': 'جاری ہے',
      'status_resolved': 'حل ہو گیا',
      'status_rejected': 'مسترد',
      'status_critical': 'شدید انتباہ',
      'cat_water': 'پانی کی فراہمی', 'cat_sanitation': 'صفائی',
      'cat_roads': 'سڑکیں اور بنیادی ڈھانچہ', 'cat_electricity': 'بجلی',
      'cat_environment': 'ماحولیات', 'view_all': 'سب دیکھیں',
      'report_civic_issue': 'شہری مسئلہ درج کریں',
      'new_report': 'نئی رپورٹ',
      'recent_panchayat_issues': 'حالیہ پنچایت مسائل',
      'village_projects': 'گاؤں کے منصوبے',
      'field_worker_portal': 'فیلڈ ورکر پورٹل',
      'assigned_work': 'تفویض شدہ کام', 'tasks': 'کام',
      'high_priority': 'اعلیٰ ترجیح', 'completed_tasks': 'مکمل',
      'this_month': 'اس مہینے', 'my_field_assignments': 'میری فیلڈ ڈیوٹیاں',
      'assigned_field_work': 'تفویض شدہ فیلڈ کام',
      'accept_work': 'کام قبول کریں', 'fill_inspection': 'معائنہ فارم بھریں',
      'confirm_dispatch': 'ارسال کی تصدیق کریں',
      'confirm_start_nav': 'تصدیق کریں اور نیویگیشن شروع کریں',
      'field_inspection_title': 'فیلڈ معائنہ فارم',
      'technical_cause': 'شناخت شدہ تکنیکی وجہ',
      'repair_time': 'مرمت کا متوقع وقت (گھنٹے)',
      'materials_required': 'ضروری مواد',
      'save_inspection': 'معائنہ نوٹس محفوظ کریں',
      'upload_before_photo': 'مرمت سے پہلے کی تصویر',
      'proceed_completion': 'کام مکمل کرنے کے لیے آگے بڑھیں',
      'upload_after_photo': 'مرمت کے بعد کی تصویر',
      'submit_completion': 'کام مکمل جمع کروائیں',
      'work_completed': 'کام مکمل ہو گیا!',
      'work_completed_desc': 'پنچایت ایڈمن سے حتمی تصدیق کے لیے درخواست کی گئی۔',
      'back_to_worker_dashboard': 'ورکر ڈیش بورڈ پر واپس',
      'daily_attendance': 'روزانہ حاضری کی صورتحال',
      'checked_in_field': 'حیثیت: چیک ان — فیلڈ میں',
      'check_out_today': 'آج چیک آؤٹ کریں',
      'admin_console': 'انتظامی کنٹرول',
      'issue_queue': 'شکایت قطار', 'employees': 'ملازمین', 'attendance': 'حاضری',
      'emergency_sos': 'ہنگامی SOS', 'approve_close': 'منظور کریں اور بند کریں',
      'user_profile': 'صارف پروفائل', 'edit_profile': 'پروفائل ترمیم کریں',
      'change_language': 'زبان تبدیل کریں', 'app_settings': 'ایپ ترتیبات',
      'help_support': 'مدد اور سپورٹ', 'about_gramone': 'گرام ون کے بارے میں',
      'sign_out': 'سائن آؤٹ', 'save_changes': 'تبدیلیاں محفوظ کریں',
      'full_name': 'پورا نام', 'email': 'ای میل', 'phone': 'فون نمبر',
      'welcome_back': 'واپس خوش آمدید', 'sign_in': 'سائن ان',
      'forgot_password': 'پاس ورڈ بھول گئے؟', 'password': 'پاس ورڈ',
      'select_language': 'زبان منتخب کریں / Select Language',
      'choose_language': 'اپنی پسندیدہ زبان منتخب کریں',
      'confirm_language': 'زبان کی تصدیق کریں', 'change_app_language': 'ایپ کی زبان تبدیل کریں',
      'notifications': 'اطلاعات', 'unauthorized_access': 'رسائی سے انکار',
      'unauthorized_msg': 'آپ کے عہدے کو اس اسکرین تک رسائی کی اجازت نہیں ہے۔',
      'back_to_dashboard': 'ڈیش بورڈ پر واپس',
      'offline_banner': 'آف لائن — آن لائن ہونے پر تبدیلیاں خود بخود ہم آہنگ ہوں گی',
      'skip': 'چھوڑیں', 'next': 'اگلا', 'get_started': 'شروع کریں',
      'welcome_to_gramone': 'گرام ون میں خوش آمدید',
      'select_role': 'جاری رکھنے کے لیے اپنا کردار منتخب کریں۔',
      'confirm': 'تصدیق', 'cancel': 'منسوخ', 'retry': 'دوبارہ کوشش',
      'loading': 'لوڈ ہو رہا ہے...', 'no_data': 'ڈیٹا دستیاب نہیں',
      'error_occurred': 'کچھ غلط ہو گیا', 'approve': 'منظور کریں',
    },
  };

  // ─────────────────────────────────────────────────────────────────────────
  // SAFE TRANSLATION ENGINE — 4-tier fallback
  // ─────────────────────────────────────────────────────────────────────────
  String tr(String key, {String? fallback}) {
    // 1. Current locale
    final localeMap = _strings[_currentLocale];
    if (localeMap != null) {
      final val = localeMap[key];
      if (val != null && val.isNotEmpty) return val;
    }
    // 2. Developer inline fallback
    if (fallback != null && fallback.isNotEmpty) return fallback;
    // 3. English default
    final enVal = _strings['en']?[key];
    if (enVal != null && enVal.isNotEmpty) return enVal;
    // 4. Raw key (never null, never empty string)
    return key;
  }
}
