"""add core domain schema

Revision ID: 94138b2c890c
Revises: 
Create Date: 2026-08-12 23:15:00.964109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '94138b2c890c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('villages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_villages'))
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.Enum('water_node', name='device_type'), server_default=sa.text("'water_node'"), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], name=op.f('fk_devices_village_id_villages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('device_id', name=op.f('uq_devices_device_id'))
    )
    op.create_index(op.f('ix_devices_village_id'), 'devices', ['village_id'], unique=False)
    op.create_table('impact_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('water', 'education', 'civic', 'other', name='issue_category'), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'prioritized', 'sponsored', 'resolved', 'impact_verified', name='impact_case_status'), server_default=sa.text("'open'"), nullable=False),
    sa.Column('affected_population', sa.Integer(), nullable=True),
    sa.Column('sdg', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], name=op.f('fk_impact_cases_village_id_villages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_cases')),
    sa.UniqueConstraint('reference', name=op.f('uq_impact_cases_reference'))
    )
    op.create_index(op.f('ix_impact_cases_status'), 'impact_cases', ['status'], unique=False)
    op.create_index(op.f('ix_impact_cases_village_id'), 'impact_cases', ['village_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('citizen', 'panchayat', 'csr', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], name=op.f('fk_users_village_id_villages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('csr_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('org_name', sa.String(length=160), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('focus_areas', postgresql.ARRAY(sa.String(length=20)), nullable=True),
    sa.Column('preferred_sdgs', postgresql.ARRAY(sa.String(length=16)), nullable=True),
    sa.Column('preferred_state', sa.String(length=80), nullable=True),
    sa.Column('preferred_districts', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('min_budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_csr_profiles_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_csr_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_csr_profiles_user_id'))
    )
    op.create_table('impact_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('impact_case_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('severity_component', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('population_component', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('evidence_component', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('time_component', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('infrastructure_component', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('scoring_version', sa.String(length=32), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['impact_case_id'], ['impact_cases.id'], name=op.f('fk_impact_scores_impact_case_id_impact_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_scores')),
    sa.UniqueConstraint('impact_case_id', name=op.f('uq_impact_scores_impact_case_id'))
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('water', 'education', 'civic', 'other', name='issue_category'), nullable=False),
    sa.Column('subcategory', sa.String(length=80), nullable=True),
    sa.Column('source', sa.Enum('citizen', 'panchayat', 'hardware', 'system', name='issue_source'), nullable=False),
    sa.Column('status', sa.Enum('reported', 'ai_processed', 'correlated', 'verified', 'prioritized', 'open', 'assigned', 'in_progress', 'resolved', 'impact_verified', name='issue_status'), server_default=sa.text("'reported'"), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('impact_case_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['impact_case_id'], ['impact_cases.id'], name=op.f('fk_issues_impact_case_id_impact_cases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_issues_reported_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], name=op.f('fk_issues_village_id_villages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issues')),
    sa.UniqueConstraint('reference', name=op.f('uq_issues_reference'))
    )
    op.create_index(op.f('ix_issues_category'), 'issues', ['category'], unique=False)
    op.create_index(op.f('ix_issues_created_at'), 'issues', ['created_at'], unique=False)
    op.create_index(op.f('ix_issues_impact_case_id'), 'issues', ['impact_case_id'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.create_index(op.f('ix_issues_village_id'), 'issues', ['village_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('info', 'issue_status', 'impact_update', 'project_update', 'sponsorship_update', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('impact_case_id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('estimated_budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Enum('created', 'open_for_collaboration', 'sponsored', 'in_progress', 'completed', 'impact_verified', name='project_status'), server_default=sa.text("'created'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['impact_case_id'], ['impact_cases.id'], name=op.f('fk_projects_impact_case_id_impact_cases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], name=op.f('fk_projects_village_id_villages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_impact_case_id'), 'projects', ['impact_case_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_village_id'), 'projects', ['village_id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('sensor_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_telemetry_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry'))
    )
    op.create_index(op.f('ix_telemetry_device_id'), 'telemetry', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    op.create_table('csr_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csr_profile_id', sa.Integer(), nullable=False),
    sa.Column('impact_case_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('scoring_version', sa.String(length=32), nullable=False),
    sa.Column('match_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('impact_case_id IS NOT NULL OR project_id IS NOT NULL', name=op.f('ck_csr_matches_csr_matches_target_check')),
    sa.ForeignKeyConstraint(['csr_profile_id'], ['csr_profiles.id'], name=op.f('fk_csr_matches_csr_profile_id_csr_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['impact_case_id'], ['impact_cases.id'], name=op.f('fk_csr_matches_impact_case_id_impact_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_csr_matches_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_csr_matches'))
    )
    op.create_index(op.f('ix_csr_matches_csr_profile_id'), 'csr_matches', ['csr_profile_id'], unique=False)
    op.create_index(op.f('ix_csr_matches_impact_case_id'), 'csr_matches', ['impact_case_id'], unique=False)
    op.create_index(op.f('ix_csr_matches_project_id'), 'csr_matches', ['project_id'], unique=False)
    op.create_table('issue_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.Enum('citizen_report', 'multiple_citizen_reports', 'panchayat_verification', 'hardware_telemetry', 'uploaded_image', 'related_issue', name='evidence_type'), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_issue_evidence_issue_id_issues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_evidence'))
    )
    op.create_index(op.f('ix_issue_evidence_issue_id'), 'issue_evidence', ['issue_id'], unique=False)
    op.create_table('issue_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.Enum('reported', 'ai_processed', 'correlated', 'verified', 'prioritized', 'open', 'assigned', 'in_progress', 'resolved', 'impact_verified', name='issue_status'), nullable=True),
    sa.Column('new_status', sa.Enum('reported', 'ai_processed', 'correlated', 'verified', 'prioritized', 'open', 'assigned', 'in_progress', 'resolved', 'impact_verified', name='issue_status'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_issue_history_changed_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_issue_history_issue_id_issues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_history'))
    )
    op.create_index(op.f('ix_issue_history_issue_id'), 'issue_history', ['issue_id'], unique=False)
    op.create_table('sponsorships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('csr_profile_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'active', 'completed', 'cancelled', name='sponsorship_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['csr_profile_id'], ['csr_profiles.id'], name=op.f('fk_sponsorships_csr_profile_id_csr_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sponsorships_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sponsorships'))
    )
    op.create_index(op.f('ix_sponsorships_csr_profile_id'), 'sponsorships', ['csr_profile_id'], unique=False)
    op.create_index(op.f('ix_sponsorships_project_id'), 'sponsorships', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsorships_project_id'), table_name='sponsorships')
    op.drop_index(op.f('ix_sponsorships_csr_profile_id'), table_name='sponsorships')
    op.drop_table('sponsorships')
    op.drop_index(op.f('ix_issue_history_issue_id'), table_name='issue_history')
    op.drop_table('issue_history')
    op.drop_index(op.f('ix_issue_evidence_issue_id'), table_name='issue_evidence')
    op.drop_table('issue_evidence')
    op.drop_index(op.f('ix_csr_matches_project_id'), table_name='csr_matches')
    op.drop_index(op.f('ix_csr_matches_impact_case_id'), table_name='csr_matches')
    op.drop_index(op.f('ix_csr_matches_csr_profile_id'), table_name='csr_matches')
    op.drop_table('csr_matches')
    op.drop_index(op.f('ix_telemetry_timestamp'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_device_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_projects_village_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_impact_case_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_issues_village_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_impact_case_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_created_at'), table_name='issues')
    op.drop_index(op.f('ix_issues_category'), table_name='issues')
    op.drop_table('issues')
    op.drop_table('impact_scores')
    op.drop_table('csr_profiles')
    op.drop_table('users')
    op.drop_index(op.f('ix_impact_cases_village_id'), table_name='impact_cases')
    op.drop_index(op.f('ix_impact_cases_status'), table_name='impact_cases')
    op.drop_table('impact_cases')
    op.drop_index(op.f('ix_devices_village_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('villages')
    # ### end Alembic commands ###