"""add assigned_to and impact case workflow states

Revision ID: e457a57f8afe
Revises: 94138b2c890c
Create Date: 2026-08-13 00:02:52.432887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e457a57f8afe'
down_revision: Union[str, None] = '94138b2c890c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extend the native impact_case_status enum with the workflow states
    # ASSIGNED and IN_PROGRESS required by the issue/intake milestone.
    op.execute("ALTER TYPE impact_case_status ADD VALUE IF NOT EXISTS 'assigned'")
    op.execute("ALTER TYPE impact_case_status ADD VALUE IF NOT EXISTS 'in_progress'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impact_cases', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_impact_cases_assigned_to_users'), 'impact_cases', 'users', ['assigned_to'], ['id'], ondelete='RESTRICT')
    op.add_column('issues', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_issues_assigned_to_users'), 'issues', 'users', ['assigned_to'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_issues_assigned_to_users'), 'issues', type_='foreignkey')
    op.drop_column('issues', 'assigned_to')
    op.drop_constraint(op.f('fk_impact_cases_assigned_to_users'), 'impact_cases', type_='foreignkey')
    op.drop_column('impact_cases', 'assigned_to')
    # ### end Alembic commands ###

    # PostgreSQL does not support removing enum values, so 'assigned' and
    # 'in_progress' stay members of impact_case_status after a downgrade.